spring.application.name=cursoservice
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.mongodb.uri=mongodb://teste:teste@localhost:27017/curso_db?authSource=admin

resilience4j.circuitbreaker.instances.alunoService.sliding-window-size=5
resilience4j.circuitbreaker.instances.alunoService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.alunoService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.alunoService.permitted-number-of-calls-in-half-open-state=3